name: fieldwork_2021
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - bleach=3.3.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.25
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - charls=2.2.0
  - cryptography=3.4.7
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype
  - gettext=0.19.8.1
  - giflib=5.1.4
  - graphite2=1.3.13
  - harfbuzz=2.8.1
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - imagecodecs-lite
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=3.0.0
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server
  - jupyterlab=3.0.14
  - jupyterlab_pygments
  - jupyterlab_server=2.4.0
  - jxrlib=1.1
  - krb5=1.19.1
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.76.1
  - libdeflate=1.7
  - libffi=3.3
  - libglib=2.68.2
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.15
  - libopencv=4.5.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libzopfli=1.0.3
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - mistune=0.8.4
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio
  - notebook=6.4.0
  - numpy=1.20.3
  - opencv=4.5.1
  - openjpeg=2.3.0
  - openssl
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.1.2
  - pixman=0.40.0
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - py-opencv=4.5.1
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.4
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pyzmq=20.0.0
  - requests=2.25.1
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - send2trash=1.5.0
  - setuptools
  - six=1.15.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sqlite=3.35.5
  - terminado=0.9.4
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2020.6.3
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2021a
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - x264=1!161.3030
  - xz=5.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - cycler==0.10.0
    - imglyb==1.0.0
    - imutils==0.5.4
    - jgo==1.0.1
    - jpype1==1.2.1
    - kiwisolver==1.3.1
    - matplotlib==3.4.2
    - pillow==8.2.0
    - psutil==5.8.0
    - pyimagej==1.0.0
    - pytesseract==0.3.7
    - scyjava==1.1.0
    - seaborn==0.11.1
    - xarray==0.18.2
